---
driver:
  name: vagrant
  synced_folders:
  - ["../", "/vagrant"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: trusty64

suites:
  - name: railsbox
    run_list:
      - railsbox
